export const userConstants = {
  SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',
};

export const viewConstants = {
  MATERIALS: "MATERIALS",
  ACTIVITIES: "ACTIVITIES",
  STORIES: "STORIES",
  WORDSEARCH: "WORDSEARCH",
};

export const activityConstants = {
  STORY: "STORY"
};

export const remoteDbConstants = {
  UPLOAD_REQUEST: 'USERS_UPLOAD_REQUEST',
  UPLOAD_SUCCESS: 'USERS_UPLOAD_SUCCESS',
  UPLOAD_FAILURE: 'USERS_UPLOAD_FAILURE',
  DOWNLOAD_REQUEST: 'DOWNLOAD_REQUEST',
  DOWNLOAD_SUCCESS: 'DOWNLOAD_SUCCESS',
  DOWNLOAD_FAILURE: 'DOWNLOAD_FAILURE',
};
